// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2fAT6Ivn84I1hr-Ia_8h_h7dn-yXSDm0',
    appId: '1:483636251174:web:f6274a228aec626605b4e7',
    messagingSenderId: '483636251174',
    projectId: 'moksha-app-37cd9',
    authDomain: 'moksha-app-37cd9.firebaseapp.com',
    storageBucket: 'moksha-app-37cd9.firebasestorage.app',
    measurementId: 'G-2SMBH0J333',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC30SCmAJxCXYpI7v_bwZMecsNJK41NdIQ',
    appId: '1:483636251174:android:3743d1f1a6a96bb005b4e7',
    messagingSenderId: '483636251174',
    projectId: 'moksha-app-37cd9',
    storageBucket: 'moksha-app-37cd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLpkE2pvJ1klEBQzYaTNmysr7gH7fn_O8',
    appId: '1:483636251174:ios:0ed442b7d818358f05b4e7',
    messagingSenderId: '483636251174',
    projectId: 'moksha-app-37cd9',
    storageBucket: 'moksha-app-37cd9.firebasestorage.app',
    iosClientId: '483636251174-bm16d4losbobcp6s5nlcfdmsdfq8bup5.apps.googleusercontent.com',
    iosBundleId: 'com.kahani.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLpkE2pvJ1klEBQzYaTNmysr7gH7fn_O8',
    appId: '1:483636251174:ios:08191912aee209dc05b4e7',
    messagingSenderId: '483636251174',
    projectId: 'moksha-app-37cd9',
    storageBucket: 'moksha-app-37cd9.firebasestorage.app',
    iosClientId: '483636251174-v42c0h8fi99d5sjssv9lbg7okim1s8l7.apps.googleusercontent.com',
    iosBundleId: 'com.example.kahaniApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2fAT6Ivn84I1hr-Ia_8h_h7dn-yXSDm0',
    appId: '1:483636251174:web:9d4af27906b0c3f405b4e7',
    messagingSenderId: '483636251174',
    projectId: 'moksha-app-37cd9',
    authDomain: 'moksha-app-37cd9.firebaseapp.com',
    storageBucket: 'moksha-app-37cd9.firebasestorage.app',
    measurementId: 'G-PS7YFE18SD',
  );

}