// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtL78105DKTZFD2lJjFC43Z_GQ0u4QfXM',
    appId: '1:990150681574:web:18a3f05013b3075e9cec27',
    messagingSenderId: '990150681574',
    projectId: 'chat-app-b3ea4',
    authDomain: 'chat-app-b3ea4.firebaseapp.com',
    storageBucket: 'chat-app-b3ea4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtIFzHhNzQ4zjZAHqnjs9U2j8l1IGd4Lg',
    appId: '1:990150681574:android:e07b5dec3dbc81df9cec27',
    messagingSenderId: '990150681574',
    projectId: 'chat-app-b3ea4',
    storageBucket: 'chat-app-b3ea4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHmTU-pkWFEkqdVNAXNnqZJNQCxPUlDS8',
    appId: '1:990150681574:ios:a580a4ea004163789cec27',
    messagingSenderId: '990150681574',
    projectId: 'chat-app-b3ea4',
    storageBucket: 'chat-app-b3ea4.firebasestorage.app',
    iosBundleId: 'com.kahani.app.kahaniApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHmTU-pkWFEkqdVNAXNnqZJNQCxPUlDS8',
    appId: '1:990150681574:ios:a580a4ea004163789cec27',
    messagingSenderId: '990150681574',
    projectId: 'chat-app-b3ea4',
    storageBucket: 'chat-app-b3ea4.firebasestorage.app',
    iosBundleId: 'com.kahani.app.kahaniApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJyrYw8y71Xegn1TkJ41R6KtIRxkzktUs',
    appId: '1:990150681574:web:c6f89bafb486f6c29cec27',
    messagingSenderId: '990150681574',
    projectId: 'chat-app-b3ea4',
    authDomain: 'chat-app-b3ea4.firebaseapp.com',
    storageBucket: 'chat-app-b3ea4.firebasestorage.app',
  );
}
