import 'package:flutter/material.dart';
import 'package:kahani_app/presentation%20/auth/signup/signup_view.dart';
import 'package:kahani_app/services/google_signin_service.dart';
import 'core/utils/theme.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Firebase init
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Google Sign-In init
  await GoogleSignInService().initialize(
    serverClientId: "483636251174-ivros4mu1nii96q3d583fgdoiqci3sbs.apps.googleusercontent.com", // OR your Web client ID
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'AI Story Generator',
      theme: AppTheme.darkTheme, // centralized theme
      home: const SignUpView(), // MVVM SignUp screen
    );
  }
}
